name: "oci-digest-action"
description: "Github Action that retrieve OCI image digests from a container registry"
inputs:
  image:
    description: "The image to fetch the image for. If this input parameter is an array of images, all images will be processed"
    required: true
  os:
    description: "The OS to use instead of the running OS for choosing images"
    required: false
  arch:
    description: "The ARCH to use instead of the architecture of the machine for choosing images"
    required: false
  variant:
    description: "The VARIANT to use instead of the running architecture variant for choosing images"
    required: false
outputs:
  digest:
    description: >
      The digest of the given image, if the image exists. When the input image is an array, the digest will also be
      an array where each element matches the corresponding image entry.
  image:
    description: "The given input image(or array of images). This output is for convenience when using the polagoab/oci-revision-tagger-action"
runs:
  using: "node20"
  main: "dist/index.js"
